Traceback (most recent call last):
  File "C:\Users\Eck\Desktop\Projetos\assistenteV3\Main\main.py", line 380, in <module>
    main_menu()
  File "C:\Users\Eck\Desktop\Projetos\assistenteV3\Main\main.py", line 365, in main_menu
    windows[0].activate()
  File "C:\Users\Eck\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
  File "C:\Users\Eck\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 0 - A operação foi concluída com êxito.
