Traceback (most recent call last):
  File "C:\Users\Erick\Desktop\Projetos\assistenteV3\Main\main.py", line 334, in <module>
    main_menu(main_threading, tray_icon_manager)
  File "C:\Users\Erick\Desktop\Projetos\assistenteV3\Main\main_menu.py", line 68, in main_menu
    main_menu(main_threading_callback, tray_icon_manager_callback)
  File "C:\Users\Erick\Desktop\Projetos\assistenteV3\Main\main_menu.py", line 43, in main_menu
    manager.run()
  File "C:\Users\Erick\Desktop\Projetos\assistenteV3\Config\keys.py", line 87, in run
    label, max_keys = self.choose_label_to_edit()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erick\Desktop\Projetos\assistenteV3\Config\keys.py", line 68, in choose_label_to_edit
    return main_menu()
           ^^^^^^^^^^^
  File "C:\Users\Erick\Desktop\Projetos\assistenteV3\Main\main_menu.py", line 68, in main_menu
    main_menu(main_threading_callback, tray_icon_manager_callback)
  File "C:\Users\Erick\Desktop\Projetos\assistenteV3\Main\main_menu.py", line 68, in main_menu
    main_menu(main_threading_callback, tray_icon_manager_callback)
  File "C:\Users\Erick\Desktop\Projetos\assistenteV3\Main\main_menu.py", line 16, in main_menu
    clear_console()
  File "C:\Users\Erick\Desktop\Projetos\assistenteV3\Class\shared.py", line 19, in clear_console
    print('\033c')
OSError: [WinError 233] Não há processo no outro extremo do pipe
